[JSF-13494] common gallery client
airslateinc/php-client pull request #250
Opened 2020-11-06 13:01 UTC by p-ponomarenko

2020-11-11 09:33 UTC, AllPDFfillersGoToHeaven requested changes

2020-11-11 09:33 UTC, AllPDFfillersGoToHeaven commented on src/Models/Gallery/AddGalleryItems.php
> +class AddGalleryItems extends AbstractModel
AddGalleryItem а не AddGalleryItem

2020-11-11 09:33 UTC, AllPDFfillersGoToHeaven commented on src/Services/GalleryService.php
> +    public function getGalleryItemsByUser(array $types): array
getGalleryItemsByUser переименовать в getGalleryItemsByCurrentUser в слейтах тоже

2020-12-17 08:41 UTC, AllPDFfillersGoToHeaven submitted a review, later dismissed

2020-12-17 08:52 UTC, soroka-pdffiller approved these changes

2020-12-17 08:52 UTC, andriiharbar approved these changes

2020-12-17 08:52 UTC, merged