HFB-2106 add content_version to document create model
airslateinc/php-client pull request #255
Opened 2020-12-16 14:57 UTC by ivan-nezhura

2020-12-16 15:20 UTC, StAngerGordun approved these changes

2020-12-16 15:26 UTC, StAngerGordun requested changes

2020-12-16 15:26 UTC, StAngerGordun commented on src/Models/Document/Create.php
> +        if (!empty($this->contentVersion)) {
https://github.com/airslateinc/slates-api/pull/3626#discussion_r544387348

2020-12-16 16:18 UTC, ivan-nezhura commented on src/Models/Document/Create.php
> +        if (!empty($this->contentVersion)) {
как свойсто документа - было в ТЗ

2020-12-17 14:30 UTC, AlexanderTereshchenko approved these changes

2020-12-17 14:57 UTC, StAngerGordun approved these changes

2020-12-17 14:57 UTC, merged