[AAD-2459] Added `receiveEmailTemplate` and `getLoginLink` methods.
airslateinc/php-client pull request #282
Opened 2021-03-31 06:21 UTC by demchenkooleh

2021-04-01 11:23 UTC, YShershnov commented on src/Models/Notifications/EmailTemplatePreviews.php
> +            "attributes" => [
nit: везде одинарные, а тут двойные кавычки

2021-04-01 11:24 UTC, YShershnov commented on src/Models/Notifications/EmailTemplatePreviews.php
> +    /** @return string */
nit: мы вроде если и делаем пхпдок для методов, то делаем его многострочным

2021-04-01 11:24 UTC, YShershnov commented on src/Services/NotificationsService.php
> +    public function receiveEmailTemplate(EmailTemplatePreviews $notification)
тут действительно нельзя указать возвращаемый тип?

2021-04-01 11:30 UTC, rostyslavkhaniukov requested changes

2021-04-01 11:30 UTC, rostyslavkhaniukov commented on src/Services/FlowsService.php
> +    public function getLoginLink(string $flowUid, string $packetUId, string $roleUId, string $userUId)
це ж ніби не flows service

2021-04-01 11:30 UTC, rostyslavkhaniukov commented on src/Services/NotificationsService.php
> +    public function receiveEmailTemplate(EmailTemplatePreviews $notification)
та по ідеї якесь entity треба робити

2021-04-01 11:32 UTC, demchenkooleh commented on src/Models/Notifications/EmailTemplatePreviews.php
> +            "attributes" => [
Сорри. Убирал и навернео не копирнул с вендора папки новые изменения. Убираю

2021-04-01 11:32 UTC, demchenkooleh commented on src/Models/Notifications/EmailTemplatePreviews.php
> +    /** @return string */
Ростик мне наоборот сказал. Или это при переходе на 7.4 ?

2021-04-01 11:33 UTC, demchenkooleh commented on src/Services/FlowsService.php
> +    public function getLoginLink(string $flowUid, string $packetUId, string $roleUId, string $userUId)
Испарвляю. Делал когда думал, что это все касается флоу. Из за этого и в слейтах переношу с модуля Флоу

2021-04-01 11:56 UTC, demchenkooleh commented on src/Services/NotificationsService.php
> +    public function receiveEmailTemplate(EmailTemplatePreviews $notification)
Посмотрел на нотификейшен апи. Теперь там вроде как возвращает Document и я смогу обернуть. Попробую

2021-04-01 12:03 UTC, demchenkooleh commented on src/Models/Notifications/EmailTemplatePreviews.php
> +    /** @return string */
Для свойств тоже многострочным делаем теперь ?

2021-04-07 08:56 UTC, rostyslavkhaniukov commented on src/Models/Packet/AssignRole.php
> +                'skip_email' => $skipEmail
```suggestion
                'skip_email' => $skipEmail,
```

2021-04-07 08:56 UTC, rostyslavkhaniukov approved these changes

2021-04-07 08:56 UTC, demchenkooleh commented on src/Models/Packet/AssignRole.php
> +                'skip_email' => $skipEmail
Ніяк не звикну до коми в кінці ....  сорі

2021-04-07 08:58 UTC, rostyslavkhaniukov commented on src/Services/RolesService.php
> +        return \GuzzleHttp\json_decode($response->getBody(), true);
Давай в entity обгорнемо

2021-04-07 12:32 UTC, demchenkooleh commented on src/Services/RolesService.php
> +        return \GuzzleHttp\json_decode($response->getBody(), true);
Вже зробив. Затещу і залью

2021-04-08 14:15 UTC, rostyslavkhaniukov commented on src/Services/NotificationsService.php
> +        return Document::createFromOne($body);
А чого Document?

2021-04-08 14:16 UTC, rostyslavkhaniukov commented on src/Services/NotificationsService.php
> +        return Document::createFromOne($body);
Документ - це ж трохи не те, це та штука у якої є філди)
тут апі навряд віддає документ)

2021-04-08 14:36 UTC, rostyslavkhaniukov approved these changes

2021-04-08 14:43 UTC, YShershnov approved these changes

2021-04-08 14:45 UTC, merged