[WIP][ASP-4432] Added createBatchAsync method to StorageFilesService
airslateinc/php-client pull request #299
Opened 2021-08-30 11:25 UTC by ORudenkoAS

2021-08-30 15:39 UTC, v-porytskyi commented on src/Services/StorageFilesService.php
> +                //TODO: need think about handling
тобто якщо запит фейлиться ми нічого не робимо?

2021-08-30 17:59 UTC, ORudenkoAS commented on src/Services/StorageFilesService.php
> +                //TODO: need think about handling
це драфт. Запитання до Фаріда написав.

2021-09-07 08:03 UTC, OlexandrRya submitted a review, later dismissed

2021-09-15 10:00 UTC, v-porytskyi submitted a review, later dismissed

2021-09-15 10:22 UTC, faridkoch approved these changes

2021-09-15 10:34 UTC, rostyslavkhaniukov requested changes

2021-09-15 10:34 UTC, rostyslavkhaniukov commented on src/Services/StorageFilesService.php
> +    private function createPoolConfig(array &$responseCollection, Closure $userDefinedOnRejectedCallback = null): array
Давай перепишемо так, щоб не передавати по посиланню, це слизька доріжка

2021-09-15 11:22 UTC, ORudenkoAS commented on src/Services/StorageFilesService.php
> +    private function createPoolConfig(array &$responseCollection, Closure $userDefinedOnRejectedCallback = null): array
А яким чином це краще зробити, бо я через посилання зробив коли в мене виникло питання "як це зробити".
Використати ларавель колекцію я не можу, бо це додасть залежність від ларавелю на весь репнік. Вважа.ю це не правильно. Робити свій класс DTO для цього? чи робити у StorageFilesService буферне поле для збору выдповідей? Але ж його треба буде щоразу чистити.

2021-09-16 08:46 UTC, rostyslavkhaniukov approved these changes

2021-09-16 09:40 UTC, v-porytskyi approved these changes

2021-09-16 10:55 UTC, merged